Repository paion-data/Messier-61, pull requests merged in 2023-03, with the labels that each got.

#64 移除 CRA
  .github/tag-for-release.bash
  .gitignore
  README.md
  babel.config.json
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/webpack/webpack.config.js
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/src/components/HomepageFeatures/index.tsx
  jest.config.json
  package-lock.json
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  scripts/build.js
  scripts/start.js
  src/components/Graph/Graph.d.ts
  src/components/Wiki/Wiki.test.tsx
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  tsconfig.json
Labels: CI/CD, DOCUMENTATION, MERGEABLE, REFACTOR, REACT COMPONENT, TESTING

#76 Auto-generate API as part of documentation
  .eslintignore
  .github/workflows/release.yml
  .github/workflows/test.yml
  docs/docs/development/ci-cd.md
  docs/docs/development/getting-started.md
  docs/docs/intro.md
  docs/docusaurus.config.js
  docs/package.json
  docs/scripts/typedoc.js
  src/components/Wiki/plugins/EmbededGraphPlugin.tsx
  src/messier-61-env.d.ts
  tsconfig.json
Labels: CI/CD, DOCUMENTATION, MERGEABLE

#62 集成D3实时绘图
  config/webpack/webpack.config.js
  jest.config.json
  src/components/Graph/D3Graph/D3Graph.module.css
  src/components/Graph/D3Graph/D3Graph.test.tsx
  src/components/Graph/D3Graph/D3Graph.tsx
Labels: NEED CHANGES, REACT COMPONENT

#79 修复Deploy-Build documentation报错
  docs/docs/intro.md
  src/components/Graph/D3Graph/D3Graph.tsx
Labels: BUG, DOCUMENTATION, MERGEABLE

#81 修复 D3Graph TypeDoc 无法出现在文档中的问题
  docs/scripts/typedoc.js
  docs/static/img/typedoc/SubjectPredicateObject.svg
Labels: BUG, DOCUMENTATION, REVIEWABLE

#83 Externalize D3 canvas config
  src/components/Graph/D3Graph/D3Graph.module.css
  src/components/Graph/D3Graph/D3Graph.tsx
Labels: BUG, REFACTOR

#60 使用编辑器实时更新图表
  jest.config.json
  src/components/Graph/Graph.d.ts
  src/components/ID/IdGenerator.tsx
  src/components/Wiki/Editor.tsx
  src/components/Wiki/plugins/GraphPlugin.test.tsx
  src/components/Wiki/plugins/GraphPlugin.tsx
Labels: NEED CHANGES, NEED REBASE, REACT COMPONENT

#89 Fix the 404 error on sub path refresh
  config/webpack/webpack.config.js
  config/webpack/webpackDevServer.config.js
  scripts/start.js
Labels: BUG, WEBPACK
