Repository paion-data/Messier-61, pull requests merged in 2023-02, with the labels that each got.

#1 Initiate documentation
  .gitignore
  docs/.gitignore
  docs/README.md
  docs/babel.config.js
  docs/blog/2019-05-28-first-blog-post.md
  docs/blog/2019-05-29-long-blog-post.md
  docs/blog/2021-08-01-mdx-blog-post.mdx
  docs/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  docs/blog/2021-08-26-welcome/index.md
  docs/blog/authors.yml
  docs/docs/intro.md
  docs/docs/tutorial-basics/_category_.json
  docs/docs/tutorial-basics/congratulations.md
  docs/docs/tutorial-basics/create-a-blog-post.md
  docs/docs/tutorial-basics/create-a-document.md
  docs/docs/tutorial-basics/create-a-page.md
  docs/docs/tutorial-basics/deploy-your-site.md
  docs/docs/tutorial-basics/markdown-features.mdx
  docs/docs/tutorial-extras/_category_.json
  docs/docs/tutorial-extras/img/docsVersionDropdown.png
  docs/docs/tutorial-extras/img/localeDropdown.png
  docs/docs/tutorial-extras/manage-docs-versions.md
  docs/docs/tutorial-extras/translate-your-site.md
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/sidebars.js
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/src/pages/markdown-page.md
  docs/static/.nojekyll
  docs/static/img/docusaurus-social-card.jpg
  docs/static/img/docusaurus.png
  docs/static/img/favicon.ico
  docs/static/img/logo.svg
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
  docs/tsconfig.json
Labels: DOCUMENTATION

#2 Enable CI/CD
  .github/tag-for-release.bash
  .github/upversion.py
  .github/workflows/release.yml
  .github/workflows/test.yml
  .gitignore
  .mdlrc
  .yamllint
  LICENSE
  README.md
  docs/README.md
  docs/blog/2019-05-28-first-blog-post.md
  docs/blog/2019-05-29-long-blog-post.md
  docs/blog/2021-08-01-mdx-blog-post.mdx
  docs/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  docs/blog/2021-08-26-welcome/index.md
  docs/blog/authors.yml
  docs/docs/development/_category_.json
  docs/docs/development/ci-cd.md
  docs/docs/development/getting-started.md
  docs/docs/intro.md
  docs/docs/tutorial-basics/_category_.json
  docs/docs/tutorial-basics/congratulations.md
  docs/docs/tutorial-basics/create-a-blog-post.md
  docs/docs/tutorial-basics/create-a-document.md
  docs/docs/tutorial-basics/create-a-page.md
  docs/docs/tutorial-basics/deploy-your-site.md
  docs/docs/tutorial-basics/markdown-features.mdx
  docs/docs/tutorial-extras/_category_.json
  docs/docs/tutorial-extras/img/docsVersionDropdown.png
  docs/docs/tutorial-extras/img/localeDropdown.png
  docs/docs/tutorial-extras/manage-docs-versions.md
  docs/docs/tutorial-extras/translate-your-site.md
  docs/docusaurus.config.js
  docs/src/pages/index.tsx
  docs/src/pages/markdown-page.md
  markdownlint.rb
  package.json
Labels: CI/CD, DOCUMENTATION, MERGEABLE

#3 Enable prettier
  .github/workflows/release.yml
  .github/workflows/test.yml
  .prettierignore
  .prettierrc.json
  README.md
  docs/babel.config.js
  docs/docs/development/ci-cd.md
  docs/docs/development/getting-started.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/css/custom.css
  docs/src/pages/index.tsx
  package.json
  public/index.html
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
Labels: BUG, CI/CD, CONFIG, MERGEABLE

#4 Enable ESLint
  .eslintignore
  .eslintrc.json
  .github/workflows/test.yml
  docs/docs/development/ci-cd.md
  docs/docs/development/getting-started.md
  docs/package.json
  package-lock.json
  package.json
  src/App.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
Labels: BUG, CI/CD, CONFIG, DOCUMENTATION, MERGEABLE

#10 Initialize backend config module
  .eslintrc.json
  src/server/core/config.js
  src/server/core/config.test.js
Labels: CONFIG

#11 Logo and naming
  .github/tag-for-release.bash
  README.md
  docs/docs/intro.md
  docs/static/img/favicon.ico
  docs/static/img/logo.svg
Labels: CI/CD, DOCUMENTATION, MERGEABLE

#12 Enable tests in CI/CD
  .github/tag-for-release.bash
  .github/workflows/test.yml
  docs/docs/development/ci-cd.md
Labels: CI/CD, DOCUMENTATION, MERGEABLE

#13 Initial implementation of online editor
  .github/workflows/test.yml
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/Editor.js
  src/editorConfig.js
  src/index.css
  src/index.tsx
  src/logo.svg
  src/nodes/EmojiNode.js
  src/onChange.js
  src/plugins/AutoFocusPlugin.js
  src/plugins/EmoticonPlugin.js
  src/plugins/TreeViewPlugin.js
  src/themes/ExampleTheme.js
Labels: MERGEABLE, REACT COMPONENT

#16 Implement rich text editing
  .github/workflows/test.yml
  package.json
  src/App.css
  src/App.tsx
  src/Editor.js
  src/editorConfig.js
  src/images/emoji/1F600.png
  src/images/emoji/1F641.png
  src/images/emoji/1F642.png
  src/images/emoji/2764.png
  src/images/emoji/LICENSE.md
  src/images/icons/LICENSE.md
  src/images/icons/arrow-clockwise.svg
  src/images/icons/arrow-counterclockwise.svg
  src/images/icons/chat-square-quote.svg
  src/images/icons/chevron-down.svg
  src/images/icons/code.svg
  src/images/icons/journal-code.svg
  src/images/icons/journal-text.svg
  src/images/icons/justify.svg
  src/images/icons/link.svg
  src/images/icons/list-ol.svg
  src/images/icons/list-ul.svg
  src/images/icons/pencil-fill.svg
  src/images/icons/text-center.svg
  src/images/icons/text-left.svg
  src/images/icons/text-paragraph.svg
  src/images/icons/text-right.svg
  src/images/icons/type-bold.svg
  src/images/icons/type-h1.svg
  src/images/icons/type-h2.svg
  src/images/icons/type-h3.svg
  src/images/icons/type-italic.svg
  src/images/icons/type-strikethrough.svg
  src/images/icons/type-underline.svg
  src/plugins/AutoLinkPlugin.js
  src/plugins/CodeHighlightPlugin.js
  src/plugins/ListMaxIndentLevelPlugin.js
  src/plugins/ToolbarPlugin.js
  src/themes/ExampleTheme.js
Labels: CONFIG, MERGEABLE, REACT COMPONENT

#20 Remove unneeded file
  src/onChange.js
Labels: MERGEABLE

#21 New home page
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/components/Editor.js
  src/components/Wiki.css
  src/components/Wiki.test.tsx
  src/components/Wiki.tsx
  src/images/doc-icon.png
  src/images/genshin-impact.webp
  src/images/github-icon.png
  src/images/knowledge-graph.png
  src/images/wiki-icon.webp
Labels: MERGEABLE, REFACTOR, REACT COMPONENT

#25 Add project planning to README
  README.md
Labels: DOCUMENTATION

#23 Link home page to wiki page
  package-lock.json
  package.json
  src/App.tsx
  src/components/Home/Home.css
  src/components/Home/Home.test.tsx
  src/components/Home/Home.tsx
  src/components/Home/images/doc-icon.png
  src/components/Home/images/genshin-impact.webp
  src/components/Home/images/github-icon.png
  src/components/Home/images/knowledge-graph.png
  src/components/Home/images/wiki-icon.webp
  src/components/Home/index.ts
  src/components/Wiki/Editor.js
  src/components/Wiki/Wiki.css
  src/components/Wiki/Wiki.test.tsx
  src/components/Wiki/Wiki.tsx
  src/components/Wiki/images/emoji/1F600.png
  src/components/Wiki/images/emoji/1F641.png
  src/components/Wiki/images/emoji/1F642.png
  src/components/Wiki/images/emoji/2764.png
  src/components/Wiki/images/emoji/LICENSE.md
  src/components/Wiki/images/icons/LICENSE.md
  src/components/Wiki/images/icons/arrow-clockwise.svg
  src/components/Wiki/images/icons/arrow-counterclockwise.svg
  src/components/Wiki/images/icons/chat-square-quote.svg
  src/components/Wiki/images/icons/chevron-down.svg
  src/components/Wiki/images/icons/code.svg
  src/components/Wiki/images/icons/journal-code.svg
  src/components/Wiki/images/icons/journal-text.svg
  src/components/Wiki/images/icons/justify.svg
  src/components/Wiki/images/icons/link.svg
  src/components/Wiki/images/icons/list-ol.svg
  src/components/Wiki/images/icons/list-ul.svg
  src/components/Wiki/images/icons/pencil-fill.svg
  src/components/Wiki/images/icons/text-center.svg
  src/components/Wiki/images/icons/text-left.svg
  src/components/Wiki/images/icons/text-paragraph.svg
  src/components/Wiki/images/icons/text-right.svg
  src/components/Wiki/images/icons/type-bold.svg
  src/components/Wiki/images/icons/type-h1.svg
  src/components/Wiki/images/icons/type-h2.svg
  src/components/Wiki/images/icons/type-h3.svg
  src/components/Wiki/images/icons/type-italic.svg
  src/components/Wiki/images/icons/type-strikethrough.svg
  src/components/Wiki/images/icons/type-underline.svg
  src/components/Wiki/index.ts
Labels: MERGEABLE, REACT COMPONENT

#27 Move editor dependencies into its component folder
  src/components/Wiki/Editor.js
  src/components/Wiki/nodes/EmojiNode.js
  src/components/Wiki/plugins/AutoFocusPlugin.js
  src/components/Wiki/plugins/AutoLinkPlugin.js
  src/components/Wiki/plugins/CodeHighlightPlugin.js
  src/components/Wiki/plugins/EmoticonPlugin.js
  src/components/Wiki/plugins/ListMaxIndentLevelPlugin.js
  src/components/Wiki/plugins/ToolbarPlugin.js
  src/components/Wiki/plugins/TreeViewPlugin.js
  src/components/Wiki/themes/ExampleTheme.js
Labels: MERGEABLE, REFACTOR

#28 Implement Auto-Graph plugin
  package-lock.json
  package.json
  src/components/Wiki/plugins/Messier61GraphPlugin.tsx
Labels: MERGEABLE, REACT COMPONENT

#31 Re-enabling YAML & Markdown Lint check
  .github/workflows/test.yml
  docs/docs/development/ci-cd.md
  docs/docs/development/img/github-upstream-issue.png
  src/components/Wiki/images/emoji/LICENSE.md
  src/components/Wiki/images/icons/LICENSE.md
Labels: CI/CD, DOCUMENTATION, MERGEABLE

#32 Re-enabling ESLint
  .eslintignore
  .github/workflows/test.yml
  package.json
  src/App.test.tsx
  src/components/Home/Home.test.tsx
  src/components/Home/Home.tsx
Labels: CI/CD, CONFIG, MERGEABLE

#33 Remove unused files
  src/components/Wiki/Editor.js
  src/components/Wiki/nodes/EmojiNode.js
  src/components/Wiki/plugins/CodeHighlightPlugin.js
  src/components/Wiki/plugins/EmoticonPlugin.js
Labels: MERGEABLE, REFACTOR

#41 Renaming
  src/components/Wiki/Editor.js
  src/components/Wiki/themes/DefaultTheme.tsx
Labels: MERGEABLE, REFACTOR

#49 Migrate Editor component to TypeScript
  src/components/Wiki/Editor.tsx
Labels: MERGEABLE, REFACTOR, REACT COMPONENT, REVIEWABLE

#51 Add link
  src/components/Home/Home.css
  src/components/Home/Home.test.tsx
  src/components/Home/Home.tsx
Labels: MERGEABLE, UX, REACT COMPONENT

#50 Add copyright
  .eslintignore
  .github/tag-for-release.bash
  .gitignore
  .yamllint
  docs/.gitignore
  docs/babel.config.js
  docs/docs/development/ci-cd.md
  docs/docs/development/getting-started.md
  docs/docs/intro.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/src/pages/markdown-page.md
  public/index.html
  src/components/Home/Home.css
  src/components/Wiki/images/emoji/LICENSE.md
  src/components/Wiki/images/icons/LICENSE.md
  src/components/Wiki/plugins/AutoLinkPlugin.js
  src/components/Wiki/plugins/ListMaxIndentLevelPlugin.js
  src/components/Wiki/plugins/ToolbarPlugin.js
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
Labels: DOCUMENTATION, MERGEABLE

#55 修复 README 无效链接
  README.md
Labels: BUG, DOCUMENTATION, MERGEABLE

#52 完善文档
  docs/docs/development/ci-cd.md
  docs/docs/development/getting-started.md
  docs/docs/development/img/code-style-check-error.png
Labels: DOCUMENTATION, MERGEABLE

#57 Define graph data structure
  src/components/Graph/Graph.d.ts
Labels: WIP, REACT COMPONENT

#58 测试自动链接生成
  src/components/Wiki/Editor.tsx
  src/components/Wiki/plugins/UrlEmailAutoLinkPlugin.test.tsx
  src/components/Wiki/plugins/UrlEmailAutoLinkPlugin.tsx
Labels: MERGEABLE, REACT COMPONENT, TESTING
